apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
spec:
  type: NodePort
  sessionAffinity: {{ .Values.service.sessionAffinity | default "None" }}
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
