apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://go.temporal.io/helm-charts
      chart: temporal
      targetRevision: 1.6.0
      helm:
        valueFiles:
          - $values/temporal/temporal-values.yaml
    - repoURL: https://github.com/mirenchaps/home-lab-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true       # let ArgoCD delete resources removed from Git
      selfHeal: true    # let ArgoCD revert manual kubectl edits back to what Git says
